### ISSUE TITLE
Missing TIMEZONE

### ISSUE THREAD

**Issue by archont00** [texxasrulez/Caldav_Calendar#19]
First of all: thanks for making the caldav work!

The calendar plugin removes the TIMEZONE info from events DTSTART and DTEND and converts the time to UTC.

The actual time remains still correct, but time zone gets lost, which has an impact on event editing in other clients (Nextcloud / Calendar web app, Android aCalendar with DavDroid sync). **The event editors show UTC as time zone and UTC time, correspondingly.** This makes subsequent editing of an existing event times prone to errors - probably everybody expects the time in local time zone, not UTC.

E.g. for `Europe/Berlin:20180411T080000` (which is UTC + 2 hours during Daylight saving time):
* Roundcube / Caldav_Calendar shows 08:00 in calendar view and in event editor (no timezone info)
* Nextcloud / Calendar webapp shows 08:00 in calendar view and 06:00 in event editor (UTC timezone).
* Android / aCalendar shows the same as Nextcloud webapp.

The Roundcube has UTC+1 hour set as Time zone in settings (which adds +1 hour in summer automatically).

ICS downloaded from Nextcloud / Calendar webapp:
```
BEGIN:VCALENDAR
PRODID:-//Nextcloud calendar v1.6.1
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20180408T143540
DTSTAMP:20180408T143540
LAST-MODIFIED:20180408T143540
UID:FRKASPT44V5801L60MG3JU
SUMMARY:T03 08:00
CLASS:PUBLIC
STATUS:CONFIRMED
DTSTART;TZID=Europe/Berlin:20180411T080000
DTEND;TZID=Europe/Berlin:20180411T090000
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```
ICS downloaded from Roundcube / Caldav_Calendar:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Roundcube libcalendaring 1.3.3//Sabre//Sabre VObject 2.1.7//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:FRKASPT44V5801L60MG3JU
DTSTAMP;VALUE=DATE-TIME:20180408T125115Z
CREATED;VALUE=DATE-TIME:20180408T143649Z
LAST-MODIFIED;VALUE=DATE-TIME:20180408T143649Z
DTSTART;VALUE=DATE-TIME:20180411T060000Z
DTEND;VALUE=DATE-TIME:20180411T070000Z
SUMMARY:T03 08:00
SEQUENCE:0
TRANSP:TRANSPARENT
STATUS:TENTATIVE
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR
```

Roundcube Webmail 1.3.3
texxasrulez/Caldav_Calendar as of today from GitHub master branch.

**Comment by texxasrulez** [comment]
I have been working on this but not much progress. I admit I am not the best programmer, but be patient with me please. I would like to see this fixed.

**Comment by texxasrulez** [comment]
I do believe I have this one fixed. A little more testing and some minor code adjustments left and I will commit and close this thing out.

**Comment by texxasrulez** [comment]
Issue should be fixed with commit 15e98de ... 

Exported output from Roundcube / Caldav GUI ..


BEGIN:VEVENT
UID:024B9E69B5D7BE6D03DDBE4D9174C8EA-8E766A0AFF03BC51
DTSTAMP;VALUE=DATE-TIME:20190408T190121Z
CREATED;VALUE=DATE-TIME:20190408T185038Z
LAST-MODIFIED;VALUE=DATE-TIME:20190408T185038Z
DTSTART;VALUE=DATE-TIME;TZID=America/Los_Angeles:20181205T093000
DTEND;VALUE=DATE-TIME;TZID=America/Los_Angeles:20181205T103000
SUMMARY:Gene VA Appt
SEQUENCE:0
CATEGORIES:Personal
TRANSP:OPAQUE
CLASS:PUBLIC
END:VEVENT

Please verify. If nothing in a day or two, I will close this issue. 

Thanks to all for your input and help.

**Comment by archont00** [comment]
@texxasrulez : It still does not work for me (I use docker roundcube/roundcubemail:latest which is v 1.3.8) and nextcloud 15.0.5.

* Before rebuilding the docker image, I deleted the existing "caldav_*" tables from MySQL.
* Then I imported calendar/drivers/caldav/SQL/mysql.initial.sql into roundcube database.
* The only change in config.inc.php was substitution of www.domain.tld with my URL.

I can provide the dockerfile and docker-compose for easier testing, if needed.
Thanks,

**Comment by texxasrulez** [comment]
I don't have docker nor while I use it. I cannot reproduce and I cannot support every configuration known. My best advice is to say fork a version and go to town. Sorry to seem brunt but that is the beauty of open source. You can take it and customize to your needs. Good luck

**Comment by archont00** [comment]
Sure. I will try to look at it one day (I am no coder, so it may be a bit demanding). Thanks anyway.

**Comment by texxasrulez** [comment]
I am not one either so I know
